version: '3'

services:
  server:
     build:
       context: ./server
       dockerfile: Dockerfile
     ports:
       - "8080:8080"

  client_mobile:
    build:
      context: ./area_mobile
      dockerfile: Dockerfile
    volumes:
      - ./client_volume/build:/app/build

  client_web:
   build:
     context: ./area-web
   ports:
     - "8081:3000"
   depends_on:
     - client_mobile
     - server
   volumes:
     - ./client_volume/build:/app/build
