// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWV2JDj3vgnEVRF9FZzmlyADjdJ4m5ak',
    appId: '1:902810887686:web:1d933dbb7d252b8dd98587',
    messagingSenderId: '902810887686',
    projectId: 'area-25011',
    authDomain: 'area-25011.firebaseapp.com',
    databaseURL: 'https://area-25011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'area-25011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KusXOwwRjNeRJ9I3PEgUv1TxsFYh0IE',
    appId: '1:902810887686:android:c7af07ee89e1d24cd98587',
    messagingSenderId: '902810887686',
    projectId: 'area-25011',
    databaseURL: 'https://area-25011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'area-25011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSw4qSOWvDr2znsPbHlYRXehAMAww04cM',
    appId: '1:902810887686:ios:ba4e502dd2c440ebd98587',
    messagingSenderId: '902810887686',
    projectId: 'area-25011',
    databaseURL: 'https://area-25011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'area-25011.appspot.com',
    iosClientId: '902810887686-16e647nhgj87lthbi9cia6q5cv4i7d1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.areaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSw4qSOWvDr2znsPbHlYRXehAMAww04cM',
    appId: '1:902810887686:ios:b9ffcc78efa6f500d98587',
    messagingSenderId: '902810887686',
    projectId: 'area-25011',
    databaseURL: 'https://area-25011-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'area-25011.appspot.com',
    iosClientId: '902810887686-5l6s3jbbchmj5f50r5nm59b87g21tba8.apps.googleusercontent.com',
    iosBundleId: 'com.example.areaMobile.RunnerTests',
  );
}
