name: deployment

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-NAN-5-1-area-hugo.guiheneuf.git"

jobs:
  push_to_mirror:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
